name: zoo
channels:
  - pytorch
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - libffi=3.4.2
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=3.0.5
  - pip=22.1.2
  - python=3.9.13
  - python_abi=3.9
  - pytorch=1.12.0
  - readline=8.1.2
  - setuptools=63.2.0
  - sqlite=3.39.1
  - tk=8.6.12
  - typing_extensions=4.3.0
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
